### ISSUE TITLE
Weekly Scrum - March 12-19th

### ISSUE THREAD

**Issue by Souheil-Yazji** [mpfan/Mini-Shopify#57]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))

what will I do next week? (with link(s) to the relevant GitHub Issue(s))

what is holding me back? (if applicable)

**Comment by DwangDistracted** [comment]
Done this week:
- Progress on Issue #55 - Backend complete, need to finish front end work for it.

For Next Week:
- Finish Issue #55 - Front End work

Blockers:
- none

**Comment by Weebian** [comment]
Done this week:

- #58 - img size on shop list view is now restricted and updated with bootstrap-Vue

For Next week:

-

**Comment by Souheil-Yazji** [comment]
Done this week:

- Progress on Issue #15 - Implemented/updated models, updated database schema, started work on Spring security components

For Next week:

- Continue with Issue #15 - Implementing Spring Security, Adding front end components, adding api controllers.

**Comment by mpfan** [comment]
Done this week:
- #65 - Fixed home page route
- #63 - Fixed product image size

For next week:
#54 - Checkout page

**Comment by dershao** [comment]
Done this week:
- #21 - view shopping cart
- #22 - construct and edit a shopping cart

Next week:
- #70 - add cookies to persist shopping cart
