### ISSUE TITLE
Weekly Scrum - March 19-26th

### ISSUE THREAD

**Issue by DwangDistracted** [mpfan/Mini-Shopify#77]
what have I done this week? (with link(s) to the relevant GitHub Issue(s))

what will I do next week? (with link(s) to the relevant GitHub Issue(s))

what is holding me back? (if applicable)

**Comment by DwangDistracted** [comment]
Done this week:

Finished #55 

For Next Week:
TBD

Blockers:
none

**Comment by mpfan** [comment]
Done this week:
Checkout: view and controller #73 
XSS protection: #79 

For next week 
TBD

Blockers:
none

**Comment by Weebian** [comment]
Done this week:
- #53 - configure the search bar to query for shops with a similar name or description to the provided keyword

For next week
- #3 - dark mode

Blockers:
- none

**Comment by dershao** [comment]
Done this week:
- #75 Fix product images not rendering correctly on shop details page
- #78 Fix header to render shopping cart changes and remove duplicate search bars
For next week:
- #70 Add cookies to persist shopping cart sessions

**Comment by Souheil-Yazji** [comment]
Done this week:

- Progress on Issue #15 - Implemented/updated models, updated database schema, started work on Spring security components

For Next week:

- Continue with Issue #15 - Implementing Spring Security, Adding front end components, adding api controllers.

Blockers:

- Conflicting configuration merged into main.
